require 'spec_helper'

describe "User pages" do

  subject { page }

  describe "signup page" do
    before { visit signup_path }

    it { should have_content('Sign up') }
    it { should have_title(full_title('Sign up')) }
  end

  describe "profile page" do
  	#we need to fill in the comment with the appropriate code in order to make the necessary User model object used inside parenthesis 'user_path(user)',
  	#we could use Active Record to create a user with User.create, but experience shows that user factories are a more convenient way to define user objects and insert them in the database.
  	#We’ll be using the factories generated by Factory Girl, a Ruby gem

  	#With the definition in spec/factories.rb, we can create a User factory in the tests using the let command (Box 6.3) and the FactoryGirl method supplied by Factory Girl:
  	let(:user) { FactoryGirl.create(:user) }
  	before { visit user_path(user) }

  	it { should have_content(user.name) }
  	it { should have_title(user.name) }
  end
end
